In [1]:
import pandas as pd

In [22]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [8]:
type(sectors)

pandas.core.groupby.DataFrameGroupBy

In [10]:
len(sectors)

21

In [15]:
fortune["Sector"].nunique()

21

In [16]:
sectors.first()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,"Chicago, IL",96114,5176,161400
Apparel,Nike,Apparel,"Beaverton, OR",30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,"Milwaukee, WI",19330,419,27000
Chemicals,Dow Chemical,Chemicals,"Midland, MI",48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,"Irving, TX",246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction","Irving, TX",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,"Chicago, IL",67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,"Oak Brook, IL",25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
Industrials,General Electric,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
Materials,Alcoa,Metals,"New York, NY",22534,-322,60000
Media,Disney,Entertainment,"Burbank, CA",52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
Retailing,Walmart,General Merchandisers,"Bentonville, AR",482130,14694,2300000
Technology,Apple,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
Telecommunications,AT&T,Telecommunications,"Dallas, TX",146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [18]:
sectors.groups

{'Aerospace & Defense': Int64Index([ 24,  45,  60,  88, 118, 120, 209, 245, 282, 378, 389, 490, 560,
             605, 785, 788, 836, 903, 958, 987],
            dtype='int64', name='Rank'),
 'Apparel': Int64Index([91, 231, 340, 354, 448, 547, 575, 597, 683, 695, 726, 794, 877,
             882, 917],
            dtype='int64', name='Rank'),
 'Business Services': Int64Index([144, 186, 199, 204, 221, 248, 249, 294, 307, 312, 355, 392, 404,
             440, 467, 468, 481, 485, 492, 503, 545, 626, 635, 652, 677, 694,
             714, 729, 734, 735, 737, 744, 767, 776, 777, 783, 791, 792, 796,
             801, 803, 816, 819, 820, 869, 870, 886, 939, 951, 952, 993],
            dtype='int64', name='Rank'),
 'Chemicals': Int64Index([ 56, 101, 182, 189, 206, 253, 262, 277, 288, 296, 316, 538, 549,
             555, 566, 580, 613, 624, 654, 668, 717, 720, 724, 758, 761, 829,
             865, 898, 934, 949],
            dtype='int64', name='Rank'),
 'Energy': Int64Index([  2,  14,  30,  32,  42,  65,  90,  95,  98, 104,
             ...
             953, 955, 962, 966, 980, 981, 983, 995, 997, 997],
            dtype='int64', name='Rank', length=122),
 'Engineering & Construction': Int64Index([155, 156, 235, 260, 301, 314, 352, 381, 433, 478, 498, 501, 516,
             572, 576, 640, 719, 738, 822, 863, 874, 892, 929, 963, 985, 994],
            dtype='int64', name='Rank'),
 'Financials': Int64Index([  4,  16,  23,  26,  27,  29,  35,  40,  43,  49,
             ...
             920, 923, 925, 926, 936, 938, 959, 976, 988, 996],
            dtype='int64', name='Rank', length=139),
 'Food and Drug Stores': Int64Index([7, 17, 19, 87, 107, 160, 181, 595, 614, 631, 669, 756, 809, 849,
             928],
            dtype='int64', name='Rank'),
 'Food, Beverages & Tobacco': Int64Index([ 41,  44,  62,  66,  84,  94, 106, 149, 153, 161, 176, 207, 215,
             242, 266, 304, 336, 337, 362, 397, 413, 429, 452, 456, 460, 535,
             542, 567, 574, 587, 608, 615, 636, 664, 686, 702, 770, 787, 795,
             804, 889, 902, 954],
            dtype='int64', name='Rank'),
 'Health Care': Int64Index([  5,   6,  12,  21,  22,  33,  39,  46,  52,  55,  63,  72,  79,
              86, 123, 124, 125, 130, 138, 140, 141, 168, 172, 200, 201, 202,
             263, 268, 278, 286, 287, 290, 291, 305, 325, 358, 359, 372, 420,
             430, 431, 447, 457, 465, 469, 515, 527, 537, 553, 559, 583, 618,
             629, 661, 684, 693, 697, 708, 746, 749, 766, 775, 790, 799, 815,
             818, 845, 868, 881, 883, 935, 960, 965, 977, 978],
            dtype='int64', name='Rank'),
 'Hotels, Resturants & Leisure': Int64Index([109, 146, 195, 218, 241, 254, 309, 371, 444, 466, 534, 546, 557,
             562, 585, 731, 763, 764, 779, 797, 895, 915, 918, 941, 999],
            dtype='int64', name='Rank'),
 'Household Products': Int64Index([ 34, 151, 174, 256, 261, 328, 338, 345, 370, 434, 441, 450, 455,
             533, 550, 554, 601, 665, 699, 716, 856, 890, 900, 907, 932, 950,
             967, 992],
            dtype='int64', name='Rank'),
 'Industrials': Int64Index([  11,   59,   75,   93,   97,  128,  134,  148,  211,  224,  360,
              377,  396,  412,  419,  539,  544,  596,  622,  623,  630,  645,
              655,  658,  666,  674,  690,  757,  782,  789,  806,  813,  823,
              831,  832,  835,  841,  847,  866,  867,  873,  887,  942,  947,
              964, 1000],
            dtype='int64', name='Rank'),
 'Materials': Int64Index([126, 127, 170, 244, 251, 303, 321, 341, 356, 373, 375, 383, 417,
             418, 426, 435, 446, 480, 489, 514, 518, 577, 586, 616, 617, 620,
             625, 628, 637, 639, 641, 660, 667, 687, 691, 751, 774, 793, 857,
             885, 911, 982, 986],
            dtype='int64', name='Rank'),
 'Media': Int64Index([ 53,  96,  99, 203, 213, 255, 327, 366, 406, 414, 525, 530, 681,
             705, 707, 722, 741, 752, 759, 762, 821, 913, 968, 969, 989],
            dtype='int64', name='Rank'),
 'Motor Vehicles & Parts': Int64Index([  8,   9,  70, 147, 154, 169, 281, 310, 334, 339, 424, 428, 470,
             588, 591, 604, 647, 670, 718, 739, 811, 957, 961, 979],
            dtype='int64', name='Rank'),
 'Retailing': Int64Index([  1,  15,  28,  38,  47,  71,  89, 103, 111, 132, 136, 139, 143,
             145, 177, 180, 191, 196, 197, 228, 234, 237, 238, 240, 258, 267,
             269, 280, 293, 297, 299, 302, 330, 342, 346, 361, 365, 374, 379,
             380, 393, 415, 427, 439, 495, 500, 502, 511, 512, 517, 523, 582,
             592, 602, 607, 610, 621, 643, 644, 648, 657, 675, 689, 721, 748,
             771, 773, 807, 812, 824, 825, 827, 840, 876, 894, 899, 922, 937,
             940, 973],
            dtype='int64', name='Rank'),
 'Technology': Int64Index([  3,  18,  20,  25,  31,  36,  51,  54,  77, 110,
             ...
             931, 943, 944, 946, 956, 970, 971, 975, 984, 990],
            dtype='int64', name='Rank', length=102),
 'Telecommunications': Int64Index([10, 13, 37, 116, 159, 187, 292, 333, 399, 443, 461, 496, 526, 619,
             786],
            dtype='int64', name='Rank'),
 'Transportation': Int64Index([ 48,  58,  67,  68,  80, 129, 142, 208, 239, 270, 353, 390, 395,
             405, 407, 416, 432, 459, 521, 528, 570, 578, 642, 672, 709, 713,
             740, 800, 814, 858, 884, 930, 933, 945, 972, 974],
            dtype='int64', name='Rank'),
 'Wholesalers': Int64Index([ 57,  64,  92, 102, 108, 119, 122, 167, 183, 185, 212, 276, 285,
             315, 317, 320, 323, 335, 351, 357, 369, 391, 423, 463, 474, 477,
             484, 564, 581, 599, 627, 653, 685, 727, 747, 780, 808, 837, 875,
             991],
            dtype='int64', name='Rank')}

In [21]:
fortune.loc[24,]

Company                     Boeing
Sector         Aerospace & Defense
Industry     Aerospace and Defense
Location               Chicago, IL
Revenue                      96114
Profits                       5176
Employees                   161400
Name: 24, dtype: object

In [ ]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

In [29]:
sectors.get_group("Energy")
sectors.get_group("Technology")

,Company,Employees,Industry,Location,Profits,Revenue
Rank,,,,,,
3,Apple,110000,"Computers, Office Equipment","Cupertino, CA",53394,233715
18,Amazon.com,230800,Internet Services and Retailing,"Seattle, WA",596,107006
20,HP,287000,"Computers, Office Equipment","Palo Alto, CA",4554,103355
25,Microsoft,118000,Computer Software,"Redmond, WA",12193,93580
31,IBM,411798,Information Technology Services,"Armonk, NY",13190,82461
36,Alphabet,61814,Internet Services and Retailing,"Mountain View, CA",16348,74989
51,Intel,107300,Semiconductors and Other Electronic Components,"Santa Clara, CA",11420,55355
54,Cisco Systems,71833,Network and Other Communications Equipment,"San Jose, CA",8981,49161
77,Oracle,132000,Computer Software,"Redwood City, CA",9938,38226
110,Qualcomm,33000,Network and Other Communications Equipment,"San Diego, CA",5271,25281
113,EMC,72000,Computer Peripherals,"Hopkinton, MA",1990,24704
133,Danaher,81000,"Scientific,Photographic and Control Equipment","Washington, DC",3357,20909
150,Xerox,143600,Information Technology Services,"Norwalk, CT",474,18664
157,Facebook,12691,Internet Services and Retailing,"Menlo Park, CA",3688,17928
158,Jabil Circuit,161000,Semiconductors and Other Electronic Components,"St. Petersburg, FL",284,17914
164,Thermo Fisher Scientific,52400,"Scientific,Photographic and Control Equipment","Waltham, MA",1975,16965
173,Micron Technology,31800,Semiconductors and Other Electronic Components,"Boise, ID",2899,16192
194,Western Digital,76449,Computer Peripherals,"Irvine, CA",1465,14572
219,Texas Instruments,29977,Semiconductors and Other Electronic Components,"Dallas, TX",2986,13000
220,CDW,8465,Information Technology Services,"Lincolnshire, IL",403,12989
230,Cognizant Technology Solutions,221700,Information Technology Services,"Teaneck, NJ",1624,12416
233,Computer Sciences,70000,Information Technology Services,"Falls Church, VA",-8,12183
284,Liberty Interactive,22080,Internet Services and Retailing,"Englewood, CO",869,9989
295,Applied Materials,15050,Semiconductors and Other Electronic Components,"Santa Clara, CA",1377,9659
300,eBay,11600,Internet Services and Retailing,"San Jose, CA",1725,9496
308,Priceline Group,15500,Internet Services and Retailing,"Norwalk, CT",2551,9224
313,Corning,35700,Network and Other Communications Equipment,"Corning, NY",1339,9111
331,Broadcom,9950,Semiconductors and Other Electronic Components,"Irvine, CA",978,8394
385,Expedia,18730,Internet Services and Retailing,"Bellevue, WA",765,6672
386,salesforce.com,19742,Computer Software,"San Francisco, CA",-47,6667
...,...,...,...,...,...,...
778,Diebold,16000,"Computers, Office Equipment","North Canton, OH",74,2768
805,Plexus,14000,Semiconductors and Other Electronic Components,"Neenah, WI",94,2654
830,Benchmark Electronics,10500,Semiconductors and Other Electronic Components,"Angleton, TX",95,2541
834,Teradata,11300,Computer Software,"Dayton, OH",-214,2530
842,Autodesk,9500,Computer Software,"San Rafael, CA",-331,2504
854,Ciena,5345,Network and Other Communications Equipment,"Hanover, MD",12,2446
864,Mettler-Toledo International,13000,"Scientific,Photographic and Control Equipment","Columbus, OH",353,2395
871,Xilinx,3451,Semiconductors and Other Electronic Components,"San Jose, CA",648,2377
888,Maxim Integrated Products,8250,Semiconductors and Other Electronic Components,"San Jose, CA",206,2307
891,Vishay Intertechnology,22400,Semiconductors and Other Electronic Components,"Malvern, PA",-109,2301
893,Teledyne Technologies,9200,"Scientific,Photographic and Control Equipment","Thousand Oaks, CA",196,2298
896,Trimble Navigation,8451,"Scientific,Photographic and Control Equipment","Sunnyvale, CA",121,2290
904,Brocade Communications Systems,4640,Network and Other Communications Equipment,"San Jose, CA",340,2264
905,PerkinElmer,8000,"Scientific,Photographic and Control Equipment","Waltham, MA",212,2263
906,Wayfair,3809,Internet Services and Retailing,"Boston, MA",-77,2250
909,Synopsys,10284,Computer Software,"Mountain View, CA",226,2242
912,Illumina,4600,"Scientific,Photographic and Control Equipment","San Diego, CA",462,2220
914,Twitter,3898,Internet Services and Retailing,"San Francisco, CA",-521,2218
919,Akamai Technologies,6084,Computer Software,"Cambridge, MA",321,2197
927,Gartner,7834,Information Technology Services,"Stamford, CT",176,2163
931,Microchip Technology,9449,Semiconductors and Other Electronic Components,"Chandler, AZ",369,2147
943,Maximus,17000,Information Technology Services,"Reston, VA",158,2100
944,TTM Technologies,29570,Semiconductors and Other Electronic Components,"Costa Mesa, CA",-26,2096
946,Engility Holdings,9800,Information Technology Services,"Chantilly, VA",-235,2086
956,Waters,6594,"Scientific,Photographic and Control Equipment","Milford, MA",469,2042
970,Rackspace Hosting,6189,Internet Services and Retailing,"San Antonio, TX",126,2001
971,VeriFone Systems,5400,"Computers, Office Equipment","San Jose, CA",79,2001
975,Super Micro Computer,2285,"Computers, Office Equipment","San Jose, CA",102,1991
984,Nuance Communications,13500,Computer Software,"Burlington, MA",-115,1931
990,F5 Networks,4178,Network and Other Communications Equipment,"Seattle, WA",365,1920

In [33]:
sectors.max()
sectors.min()
sectors.sum()

                              Revenue  Profits  Employees
Sector
Aerospace & Defense            357940    28742     968057
Apparel                         95968     8236     346397
Business Services              272195    28227    1361050
Chemicals                      243897    22628     463651
Energy                        1517809   -73447    1188927
Engineering & Construction     153983     5304     406708
Financials                    2217159   260209    3359948
Food and Drug Stores           483769    16759    1395398
Food, Beverages & Tobacco      555967    51417    1211632
Health Care                   1614707   106114    2678289
Hotels, Resturants & Leisure   169546    20697    2484245
Household Products             234737    14428     646038
Industrials                    497581    20764    1545229
Materials                      259145     4428     638123
Media                          220764    24347     550314
Motor Vehicles & Parts         482540    25898    1082560
Retailing                     1465076    47830    6227629
Technology                    1377600   180473    3578949
Telecommunications             461834    48637     832468
Transportation                 408508    44169    1536793
Wholesalers                    444800     8233     525597

In [37]:
sectors.get_group("Apparel")["Profits"].sum()

8236

In [38]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby(["Sector","Industry"])
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [39]:
sectors.sum()

                                                                           Revenue  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                            357940
Apparel                    Apparel                                           95968
Business Services          Advertising, marketing                            22748
                           Diversified Outsourcing Services                  64829
                           Education                                          7485
                           Financial Data Services                          100778
                           Miscellaneous                                     11185
                           Temporary Help                                    34716
                           Waste Management                                  30454
Chemicals                  Chemicals                                        243897
Energy                     Energy                                            67749
                           Mining, Crude-Oil Production                     176435
                           Miscellaneous                                      3159
                           Oil and Gas Equipment, Services                   82827
                           Petroleum Refining                               705472
                           Pipelines                                        138756
                           Utilities: Gas and Electric                      343411
Engineering & Construction Engineering, Construction                         99774
                           Homebuilders                                      54209
Financials                 Commercial Banks                                 623669
                           Diversified Financials                           327075
                           Insurance: Life, Health (Mutual)                 181336
                           Insurance: Life, Health (stock)                  245551
                           Insurance: Property and Casualty (Mutual)        143682
                           Insurance: Property and Casualty (Stock)         548027
                           Real estate                                       62748
                           Securities                                        85071
Food and Drug Stores       Food and Drug Stores                             483769
Food, Beverages & Tobacco  Beverages                                         79396
                           Food Consumer Products                           238954
...                                                                            ...
Materials                  Metals                                            99925
                           Miscellaneous                                      6070
                           Packaging, Containers                            105965
Media                      Entertainment                                    186276
                           Publishing, Printing                              34488
Motor Vehicles & Parts     Motor Vehicles and Parts                         482540
Retailing                  Automotive Retailing, Services                   113823
                           General Merchandisers                            684320
                           Specialty Retailers: Apparel                     122975
                           Specialty Retailers: Other                       543958
Technology                 Computer Peripherals                              48950
                           Computer Software                                179112
                           Computers, Office Equipment                      353781
                           Information Technology Services                  166067
                           Internet Services and Retailing                  259136
                           Network and Other Communications Equipment       125697
                           Scientific,Photographic and Control Equipment     65832
                           Semiconductors and Other Electronic Components   179025
Telecommunications         Telecommunications                               461834
Transportation             Airlines                                         158948
                           Mail, Package, and Freight Delivery              105816
                           Miscellaneous                                      2148
                           Railroads                                         48554
                           Transportation Equipment                          23855
                           Transportation and Logistics                      33237
                           Trucking, Truck Leasing                           35950
Wholesalers                Miscellaneous                                      8982
                           Wholesalers: Diversified                         176138
                           Wholesalers: Electronics and Office Equipment    147906
                           Wholesalers: Food and Grocery                    111774

                                                                           Profits  \
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                             28742
Apparel                    Apparel                                            8236
Business Services          Advertising, marketing                             1549
                           Diversified Outsourcing Services                   4305
                           Education                                            69
                           Financial Data Services                           17456
                           Miscellaneous                                      2130
                           Temporary Help                                     1000
                           Waste Management                                   1718
Chemicals                  Chemicals                                         22628
Energy                     Energy                                           -13038
                           Mining, Crude-Oil Production                    -124555
                           Miscellaneous                                       476
                           Oil and Gas Equipment, Services                   -4047
                           Petroleum Refining                                31888
                           Pipelines                                          5814
                           Utilities: Gas and Electric                       30015
Engineering & Construction Engineering, Construction                          1765
                           Homebuilders                                       3539
Financials                 Commercial Banks                                 129760
                           Diversified Financials                            28548
                           Insurance: Life, Health (Mutual)                   5601
                           Insurance: Life, Health (stock)                   19731
                           Insurance: Property and Casualty (Mutual)          8031
                           Insurance: Property and Casualty (Stock)          44803
                           Real estate                                        9480
                           Securities                                        14255
Food and Drug Stores       Food and Drug Stores                              16759
Food, Beverages & Tobacco  Beverages                                         11698
                           Food Consumer Products                            19263
...                                                                            ...
Materials                  Metals                                            -2241
                           Miscellaneous                                         7
                           Packaging, Containers                              4445
Media                      Entertainment                                     25686
                           Publishing, Printing                              -1339
Motor Vehicles & Parts     Motor Vehicles and Parts                          25898
Retailing                  Automotive Retailing, Services                     2550
                           General Merchandisers                             20137
                           Specialty Retailers: Apparel                       4583
                           Specialty Retailers: Other                        20560
Technology                 Computer Peripherals                               3975
                           Computer Software                                 26457
                           Computers, Office Equipment                       58433
                           Information Technology Services                   16402
                           Internet Services and Retailing                   22232
                           Network and Other Communications Equipment        18907
                           Scientific,Photographic and Control Equipment      9346
                           Semiconductors and Other Electronic Components    24721
Telecommunications         Telecommunications                                48637
Transportation             Airlines                                          23800
                           Mail, Package, and Freight Delivery                5894
                           Miscellaneous                                       227
                           Railroads                                          9005
                           Transportation Equipment                           2438
                           Transportation and Logistics                        895
                           Trucking, Truck Leasing                            1910
Wholesalers                Miscellaneous                                        17
                           Wholesalers: Diversified                           5193
                           Wholesalers: Electronics and Office Equipment      1857
                           Wholesalers: Food and Grocery                      1166

                                                                           Employees
Sector                     Industry
Aerospace & Defense        Aerospace and Defense                              968057
Apparel                    Apparel                                            346397
Business Services          Advertising, marketing                             124100
                           Diversified Outsourcing Services                   708330
                           Education                                           46755
                           Financial Data Services                            264926
                           Miscellaneous                                       37720
                           Temporary Help                                      60020
                           Waste Management                                   119199
Chemicals                  Chemicals                                          463651
Energy                     Energy                                              70072
                           Mining, Crude-Oil Production                       149110
                           Miscellaneous                                        6700
                           Oil and Gas Equipment, Services                    225795
                           Petroleum Refining                                 244880
                           Pipelines                                           72141
                           Utilities: Gas and Electric                        420229
Engineering & Construction Engineering, Construction                          368104
                           Homebuilders                                        38604
Financials                 Commercial Banks                                  1539024
                           Diversified Financials                             329114
                           Insurance: Life, Health (Mutual)                    58801
                           Insurance: Life, Health (stock)                    202233
                           Insurance: Property and Casualty (Mutual)          133148
                           Insurance: Property and Casualty (Stock)           794123
                           Real estate                                        160579
                           Securities                                         142926
Food and Drug Stores       Food and Drug Stores                              1395398
Food, Beverages & Tobacco  Beverages                                          199107
                           Food Consumer Products                             665439
...                                                                              ...
Materials                  Metals                                             193559
                           Miscellaneous                                          52
                           Packaging, Containers                              333446
Media                      Entertainment                                      383564
                           Publishing, Printing                               166750
Motor Vehicles & Parts     Motor Vehicles and Parts                          1082560
Retailing                  Automotive Retailing, Services                     174974
                           General Merchandisers                             3408100
                           Specialty Retailers: Apparel                       770543
                           Specialty Retailers: Other                        1874012
Technology                 Computer Peripherals                               175259
                           Computer Software                                  388796
                           Computers, Office Equipment                        468085
                           Information Technology Services                    985639
                           Internet Services and Retailing                    430855
                           Network and Other Communications Equipment         299310
                           Scientific,Photographic and Control Equipment      231501
                           Semiconductors and Other Electronic Components     599504
Telecommunications         Telecommunications                                 832468
Transportation             Airlines                                           391601
                           Mail, Package, and Freight Delivery                664275
                           Miscellaneous                                        4200
                           Railroads                                          121844
                           Transportation Equipment                            59726
                           Transportation and Logistics                       124691
                           Trucking, Truck Leasing                            170456
Wholesalers                Miscellaneous                                        9200
                           Wholesalers: Diversified                           233831
                           Wholesalers: Electronics and Office Equipment      166661
                           Wholesalers: Food and Grocery                      115905

[79 rows x 3 columns]

In [40]:
fortune = pd.read_csv("fortune1000.csv", index_col="Rank")
sectors = fortune.groupby("Sector")
fortune.head()

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400

In [43]:
sectors.agg({"Revenue":"sum",
            "Profits":"sum",
            "Employees":"mean"})

                              Revenue  Profits     Employees
Sector
Aerospace & Defense            357940    28742  48402.850000
Apparel                         95968     8236  23093.133333
Business Services              272195    28227  26687.254902
Chemicals                      243897    22628  15455.033333
Energy                        1517809   -73447   9745.303279
Engineering & Construction     153983     5304  15642.615385
Financials                    2217159   260209  24172.287770
Food and Drug Stores           483769    16759  93026.533333
Food, Beverages & Tobacco      555967    51417  28177.488372
Health Care                   1614707   106114  35710.520000
Hotels, Resturants & Leisure   169546    20697  99369.800000
Household Products             234737    14428  23072.785714
Industrials                    497581    20764  33591.934783
Materials                      259145     4428  14840.069767
Media                          220764    24347  22012.560000
Motor Vehicles & Parts         482540    25898  45106.666667
Retailing                     1465076    47830  77845.362500
Technology                    1377600   180473  35087.735294
Telecommunications             461834    48637  55497.866667
Transportation                 408508    44169  42688.694444
Wholesalers                    444800     8233  13139.925000

In [45]:
df = pd.DataFrame(columns= fortune.columns)

In [46]:
for sector, data in sectors:
    highest_revenue = data.nlargest(1, "Revenue")
    df = df.append(highest_revenue)

In [47]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
109,McDonald’s,"Hotels, Resturants & Leisure",Food Services,"Oak Brook, IL",25413,4529,420000
34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
126,Alcoa,Materials,Metals,"New York, NY",22534,-322,60000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [48]:

cities = fortune.groupby("Location")

In [50]:
for sector, data in cities:
    highest_revenue = data.nlargest(1, "Revenue")
    df = df.append(highest_revenue)

In [51]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
5,McKesson,Health Care,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
109,McDonald’s,"Hotels, Resturants & Leisure",Food Services,"Oak Brook, IL",25413,4529,420000
34,Procter & Gamble,Household Products,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
11,General Electric,Industrials,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
126,Alcoa,Materials,Metals,"New York, NY",22534,-322,60000
53,Disney,Media,Entertainment,"Burbank, CA",52465,8382,185000
8,General Motors,Motor Vehicles & Parts,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
10,AT&T,Telecommunications,Telecommunications,"Dallas, TX",146801,13345,281450
48,UPS,Transportation,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
144,ManpowerGroup,Business Services,Temporary Help,"Milwaukee, WI",19330,419,27000
56,Dow Chemical,Chemicals,Chemicals,"Midland, MI",48778,7685,49495
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
155,Fluor,Engineering & Construction,"Engineering, Construction","Irving, TX",18114,413,38758
4,Berkshire Hathaway,Financials,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
41,Archer Daniels Midland,"Food, Beverages & Tobacco",Food Production,"Chicago, IL",67702,1849,32300
...,...,...,...,...,...,...,...
120,Raytheon,Aerospace & Defense,Aerospace and Defense,"Waltham, MA",23247,2074,61000
850,United Refining,Energy,Petroleum Refining,"Warren, PA",2470,82,2997
431,Zimmer Biomet Holdings,Health Care,Medical Products and Equipment,"Warsaw, IN",5998,147,17500
16,Fannie Mae,Financials,Diversified Financials,"Washington, DC",110359,10954,7300
542,Keurig Green Mountain,"Food, Beverages & Tobacco",Beverages,"Waterbury, VT",4520,498,6000
898,MPM Holdings,Chemicals,Chemicals,"Waterford, NY",2289,-83,5000
874,Granite Construction,Engineering & Construction,"Engineering, Construction","Watsonville, CA",2371,61,3200
1000,Briggs & Stratton,Industrials,Industrial Machinery,"Wauwatosa, WI",1895,46,5480
240,Toys “R” Us,Retailing,Specialty Retailers: Other,"Wayne, NJ",11802,-130,62000
785,B/E Aerospace,Aerospace & Defense,Aerospace and Defense,"Wellington, FL",2730,286,10057
383,AK Steel Holding,Materials,Metals,"West Chester, OH",6693,-509,8500
829,Platform Specialty Products,Chemicals,Chemicals,"West Palm Beach, FL",2542,-309,8200
996,New York Community Bancorp,Financials,Commercial Banks,"Westbury, NY",1902,-47,3448
456,Ingredion,"Food, Beverages & Tobacco",Food Production,"Westchester, IL",5621,402,11500
439,TravelCenters of America,Retailing,Specialty Retailers: Other,"Westlake, OH",5851,28,18450
396,Terex,Industrials,Construction and Farm Machinery,"Westport, CT",6543,146,20400
847,ITT,Industrials,Industrial Machinery,"White Plains, NY",2486,352,9700
389,Spirit AeroSystems Holdings,Aerospace & Defense,Aerospace and Defense,"Wichita, KS",6644,789,15200
849,Tops Holding,Food and Drug Stores,Food and Drug Stores,"Williamsville, NY",2472,-62,14800
674,Westinghouse Air Brake Technologies,Industrials,Industrial Machinery,"Wilmerding, PA",3308,399,13000
101,DuPont,Chemicals,Chemicals,"Wilmington, DE",27940,1953,52000
607,Fastenal,Retailing,Specialty Retailers: Other,"Winona, MN",3869,516,20746
266,Reynolds American,"Food, Beverages & Tobacco",Tobacco,"Winston-Salem, NC",10675,3253,5650
678,Skyworks Solutions,Technology,Semiconductors and Other Electronic Components,"Woburn, MA",3258,798,6700
172,Health Net,Health Care,Health Care: Insurance and Managed Care,"Woodland Hills, CA",16244,186,8584
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
506,Hanover Insurance Group,Financials,Insurance: Property and Casualty (Stock),"Worcester, MA",5034,332,4800
764,Penn National Gaming,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Wyomissing, PA",2838,1,18204
773,Bon-Ton Stores,Retailing,General Merchandisers,"York, PA",2790,-57,24100
932,Herman Miller,Household Products,"Home Equipment, Furnishings","Zeeland, MI",2142,98,7510