In [17]:
import pandas as pd
from pandas_datareader import data

In [20]:
companies = ["MSFT","GOOG","AAPL","AMZN"]

In [21]:
p =data.DataReader(name= companies, data_source="yahoo", start="2010", end="2016")

In [9]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 1511 (major_axis) x 4 (minor_axis)
Items axis: Adj Close to Volume
Major_axis axis: 2015-12-31 00:00:00 to 2009-12-31 00:00:00
Minor_axis axis: AAPL to MSFT

In [11]:
p.items

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [12]:
p.major_axis

DatetimeIndex(['2015-12-31', '2015-12-30', '2015-12-29', '2015-12-28',
               '2015-12-24', '2015-12-23', '2015-12-22', '2015-12-21',
               '2015-12-18', '2015-12-17',
               ...
               '2010-01-14', '2010-01-13', '2010-01-12', '2010-01-11',
               '2010-01-08', '2010-01-07', '2010-01-06', '2010-01-05',
               '2010-01-04', '2009-12-31'],
              dtype='datetime64[ns]', name='Date', length=1511, freq=None)

In [13]:
p.minor_axis

Index(['AAPL', 'AMZN', 'GOOG', 'MSFT'], dtype='object')

In [14]:
p.axes

[Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object'),
 DatetimeIndex(['2015-12-31', '2015-12-30', '2015-12-29', '2015-12-28',
                '2015-12-24', '2015-12-23', '2015-12-22', '2015-12-21',
                '2015-12-18', '2015-12-17',
                ...
                '2010-01-14', '2010-01-13', '2010-01-12', '2010-01-11',
                '2010-01-08', '2010-01-07', '2010-01-06', '2010-01-05',
                '2010-01-04', '2009-12-31'],
               dtype='datetime64[ns]', name='Date', length=1511, freq=None),
 Index(['AAPL', 'AMZN', 'GOOG', 'MSFT'], dtype='object')]

In [22]:
p.ndin

AttributeError: 'Panel' object has no attribute 'ndin'

In [23]:
p.dtypes

Adj Close    float64
Close        float64
High         float64
Low          float64
Open         float64
Volume       float64
dtype: object

In [24]:
p.shape

(6, 1511, 4)

In [25]:
p.shape

(6, 1511, 4)

In [26]:
p.values

array([[[  1.01339394e+02,   6.75890015e+02,   7.58880005e+02,
           5.28189010e+01],
        [  1.03322678e+02,   6.89070007e+02,   7.71000000e+02,
           5.36090930e+01],
        [  1.04689766e+02,   6.93969971e+02,   7.76599976e+02,
           5.38375780e+01],
        ...,
        [  2.74539150e+01,   1.34690002e+02,   3.09978882e+02,
           2.51570010e+01],
        [  2.74065320e+01,   1.33899994e+02,   3.11349976e+02,
           2.51488760e+01],
        [  2.69864920e+01,   1.34520004e+02,   3.07986847e+02,
           2.47669680e+01]],

       [[  1.05260002e+02,   6.75890015e+02,   7.58880005e+02,
           5.54800000e+01],
        [  1.07320000e+02,   6.89070007e+02,   7.71000000e+02,
           5.63100010e+01],
        [  1.08739998e+02,   6.93969971e+02,   7.76599976e+02,
           5.65499990e+01],
        ...,
        [  3.06257130e+01,   1.34690002e+02,   3.09978882e+02,
           3.09599990e+01],
        [  3.05728570e+01,   1.33899994e+02,   3.11349976e+02,
           3.09500010e+01],
        [  3.01042860e+01,   1.34520004e+02,   3.07986847e+02,
           3.04800000e+01]],

       [[  1.07029999e+02,   6.87750000e+02,   7.69500000e+02,
           5.61899990e+01],
        [  1.08699997e+02,   6.95489990e+02,   7.77599976e+02,
           5.67799990e+01],
        [  1.09430000e+02,   6.96440002e+02,   7.79979980e+02,
           5.68499980e+01],
        ...,
        [  3.07985710e+01,   1.35479996e+02,   3.11891449e+02,
           3.11000000e+01],
        [  3.06428570e+01,   1.36610001e+02,   3.12721039e+02,
           3.11000000e+01],
        [  3.04785710e+01,   1.37279999e+02,   3.10679321e+02,
           3.09900000e+01]],

       [[  1.04820000e+02,   6.75890015e+02,   7.58340027e+02,
           5.54199980e+01],
        [  1.07180000e+02,   6.86380005e+02,   7.66900024e+02,
           5.62900010e+01],
        [  1.06860001e+02,   6.77890015e+02,   7.66429993e+02,
           5.60600010e+01],
        ...,
        [  3.04642850e+01,   1.31809998e+02,   3.08761810e+02,
           3.06399990e+01],
        [  3.03400000e+01,   1.33139999e+02,   3.10103088e+02,
           3.05900000e+01],
        [  3.00800000e+01,   1.34520004e+02,   3.07986847e+02,
           3.04800000e+01]],

       [[  1.07010002e+02,   6.86080017e+02,   7.69500000e+02,
           5.60400010e+01],
        [  1.08580002e+02,   6.91890015e+02,   7.76599976e+02,
           5.64700010e+01],
        [  1.06959999e+02,   6.77979980e+02,   7.66690002e+02,
           5.62900010e+01],
        ...,
        [  3.06571430e+01,   1.33429993e+02,   3.11563568e+02,
           3.08500000e+01],
        [  3.04900000e+01,   1.36250000e+02,   3.11449310e+02,
           3.06200010e+01],
        [  3.04471440e+01,   1.37089996e+02,   3.10356445e+02,
           3.09800000e+01]],

       [[  4.06353000e+07,   3.74960000e+06,   1.50090000e+06,
           2.73341000e+07],
        [  2.52138000e+07,   3.51900000e+06,   1.29330000e+06,
           2.17045000e+07],
        [  3.09312000e+07,   5.73500000e+06,   1.76500000e+06,
           2.77314000e+07],
        ...,
        [  1.50476200e+08,   8.85190000e+06,   6.04850000e+06,
           4.97496000e+07],
        [  1.23432400e+08,   7.59990000e+06,   3.93780000e+06,
           3.84091000e+07],
        [  8.81027000e+07,   4.52300000e+06,   2.45540000e+06,
           3.19297000e+07]]])

In [27]:
p.items

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [28]:
p["High"]

                  AAPL        AMZN        GOOG       MSFT
Date
2015-12-31  107.029999  687.750000  769.500000  56.189999
2015-12-30  108.699997  695.489990  777.599976  56.779999
2015-12-29  109.430000  696.440002  779.979980  56.849998
2015-12-28  107.690002  675.500000  762.989990  55.950001
2015-12-24  109.000000  664.679993  751.349976  55.959999
2015-12-23  108.849998  666.599976  754.210022  55.880001
2015-12-22  107.720001  668.489990  754.849976  55.480000
2015-12-21  107.370003  669.900024  750.000000  55.349998
2015-12-18  109.519997  676.840027  754.130005  56.000000
2015-12-17  112.250000  682.500000  762.679993  56.790001
2015-12-16  111.989998  677.349976  760.590027  56.250000
2015-12-15  112.800003  671.500000  758.080017  55.900002
2015-12-14  112.680000  658.590027  748.729980  55.209999
2015-12-11  115.389999  657.880005  745.710022  55.099998
2015-12-10  116.940002  668.530029  755.849976  55.660000
2015-12-09  117.690002  679.000000  764.229980  55.869999
2015-12-08  118.599998  679.989990  764.799988  56.099998
2015-12-07  119.860001  675.460022  768.729980  55.970001
2015-12-04  119.250000  674.780029  768.489990  56.230000
2015-12-03  116.790001  682.789978  768.994995  55.770000
2015-12-02  118.110001  684.820007  775.955017  55.959999
2015-12-01  118.809998  681.000000  768.950012  55.230000
2015-11-30  119.410004  681.289978  754.929993  54.959999
2015-11-27  118.410004  680.989990  753.409973  54.080002
2015-11-25  119.230003  679.700012  752.000000  54.230000
2015-11-24  119.349998  675.799988  755.278992  54.439999
2015-11-23  119.730003  682.770020  762.708008  54.459999
2015-11-20  119.919998  668.869995  757.919983  54.299999
2015-11-19  119.750000  672.859985  742.000000  54.660000
2015-11-18  117.489998  664.880005  741.409973  53.980000
...                ...         ...         ...        ...
2010-02-12   28.805714  119.940002  266.839478  28.059999
2010-02-11   28.535715  120.419998  268.498688  28.400000
2010-02-10   28.085714  118.610001  267.157410  28.240000
2010-02-09   28.214285  119.089996  269.015320  28.340000
2010-02-08   28.268572  121.000000  269.248810  28.080000
2010-02-05   28.000000  117.650002  265.026245  28.280001
2010-02-04   28.338572  120.330002  267.261719  28.500000
2010-02-03   28.600000  119.610001  269.298462  28.790001
2010-02-02   28.045713  118.980003  265.751556  28.500000
2010-02-01   28.000000  124.860001  266.173798  28.480000
2010-01-29   28.885714  131.850006  268.747070  29.920000
2010-01-28   29.357143  127.199997  271.732635  29.870001
2010-01-27   30.082857  123.330002  272.055542  29.820000
2010-01-26   30.530001  122.980003  273.024231  29.850000
2010-01-25   29.242857  122.279999  273.163330  29.660000
2010-01-22   29.642857  127.669998  283.456390  30.200001
2010-01-21   30.472857  128.149994  291.513977  30.719999
2010-01-20   30.792856  129.199997  291.096710  30.940001
2010-01-19   30.741428  128.000000  293.302338  31.240000
2010-01-15   30.228571  129.649994  294.862213  31.240000
2010-01-14   30.065714  130.380005  295.180145  31.100000
2010-01-13   30.132856  129.710007  292.288940  30.520000
2010-01-12   29.967142  129.820007  297.147339  30.400000
2010-01-11   30.428572  132.800003  300.276978  30.760000
2010-01-08   30.285715  133.679993  299.675903  30.879999
2010-01-07   30.285715  132.320007  303.029083  30.700001
2010-01-06   30.747143  134.729996  310.907837  31.080000
2010-01-05   30.798571  135.479996  311.891449  31.100000
2010-01-04   30.642857  136.610001  312.721039  31.100000
2009-12-31   30.478571  137.279999  310.679321  30.990000

[1511 rows x 4 columns]

In [31]:
p['Volume'].head()

                  AAPL       AMZN       GOOG        MSFT
Date
2015-12-31  40635300.0  3749600.0  1500900.0  27334100.0
2015-12-30  25213800.0  3519000.0  1293300.0  21704500.0
2015-12-29  30931200.0  5735000.0  1765000.0  27731400.0
2015-12-28  26704200.0  3775800.0  1515300.0  21698000.0
2015-12-24  13570400.0  1093000.0   527200.0   9570000.0

In [37]:
p.Close

                  AAPL        AMZN        GOOG       MSFT
Date
2015-12-31  105.260002  675.890015  758.880005  55.480000
2015-12-30  107.320000  689.070007  771.000000  56.310001
2015-12-29  108.739998  693.969971  776.599976  56.549999
2015-12-28  106.820000  675.200012  762.510010  55.950001
2015-12-24  108.029999  662.789978  748.400024  55.669998
2015-12-23  108.610001  663.700012  750.309998  55.820000
2015-12-22  107.230003  663.150024  750.000000  55.349998
2015-12-21  107.330002  664.510010  747.770020  54.830002
2015-12-18  106.029999  664.140015  739.309998  54.130001
2015-12-17  108.980003  670.650024  749.429993  55.700001
2015-12-16  111.339996  675.770020  758.090027  56.130001
2015-12-15  110.489998  658.640015  743.400024  55.200001
2015-12-14  112.480003  657.909973  747.770020  55.139999
2015-12-11  113.180000  640.150024  738.869995  54.060001
2015-12-10  116.169998  662.320007  749.460022  55.270000
2015-12-09  115.620003  664.789978  751.609985  54.980000
2015-12-08  118.230003  677.330017  762.369995  55.790001
2015-12-07  118.279999  669.830017  763.250000  55.810001
2015-12-04  119.029999  672.640015  766.809998  55.910000
2015-12-03  115.199997  666.250000  752.539978  54.200001
2015-12-02  116.279999  676.010010  762.380005  55.209999
2015-12-01  117.339996  679.059998  767.039978  55.220001
2015-11-30  118.300003  664.799988  742.599976  54.349998
2015-11-27  117.809998  673.260010  750.260010  53.930000
2015-11-25  118.029999  675.340027  748.150024  53.689999
2015-11-24  118.879997  671.150024  748.280029  54.250000
2015-11-23  117.750000  678.989990  755.979980  54.189999
2015-11-20  119.300003  668.450012  756.599976  54.189999
2015-11-19  118.779999  661.270020  738.409973  53.939999
2015-11-18  117.290001  663.539978  740.000000  53.849998
...                ...         ...         ...        ...
2010-02-12   28.625713  119.660004  264.837494  27.930000
2010-02-11   28.381428  120.089996  266.466888  28.120001
2010-02-10   27.874287  117.360001  265.498199  27.990000
2010-02-09   28.027143  118.029999  266.486755  28.010000
2010-02-08   27.731428  116.830002  265.011353  27.719999
2010-02-05   27.922857  117.389999  263.928406  28.020000
2010-02-04   27.435715  115.940002  261.687958  27.840000
2010-02-03   28.461428  119.099998  268.662598  28.629999
2010-02-02   27.980000  118.120003  263.843964  28.459999
2010-02-01   27.818571  118.870003  264.787811  28.410000
2010-01-29   27.437143  125.410004  263.257751  28.180000
2010-01-28   28.469999  126.029999  265.418701  29.160000
2010-01-27   29.697144  122.750000  269.298462  29.670000
2010-01-26   29.420000  119.480003  269.457428  29.500000
2010-01-25   29.010000  120.309998  268.255249  29.320000
2010-01-22   28.250000  121.430000  273.227905  28.959999
2010-01-21   29.724285  126.620003  289.606384  30.010000
2010-01-20   30.247143  125.779999  288.329681  30.590000
2010-01-19   30.719999  127.610001  291.911407  31.100000
2010-01-15   29.418571  127.139999  288.126007  30.860001
2010-01-14   29.918571  127.349998  293.019196  30.959999
2010-01-13   30.092857  129.110001  291.648102  30.350000
2010-01-12   29.674286  127.349998  293.332153  30.070000
2010-01-11   30.015715  130.309998  298.612823  30.270000
2010-01-08   30.282858  133.520004  299.064880  30.660000
2010-01-07   30.082857  130.000000  295.130463  30.450001
2010-01-06   30.138571  132.250000  302.164703  30.770000
2010-01-05   30.625713  134.690002  309.978882  30.959999
2010-01-04   30.572857  133.899994  311.349976  30.950001
2009-12-31   30.104286  134.520004  307.986847  30.480000

[1511 rows x 4 columns]

In [39]:
p.loc["Close","2010-01-04","GOOG"]

Date
2010-01-04    311.349976
Name: GOOG, dtype: float64

In [40]:
p.iloc[4,200]

AAPL    127.000000
AMZN    369.970001
GOOG    549.476196
MSFT     41.430000
Name: 2015-03-18 00:00:00, dtype: float64

In [41]:
p.iloc[4,200,2]

549.47619599999996

In [42]:
p.to_frame()

                   Adj Close       Close        High         Low        Open  \
Date       minor
2015-12-31 AAPL   101.339394  105.260002  107.029999  104.820000  107.010002
           AMZN   675.890015  675.890015  687.750000  675.890015  686.080017
           GOOG   758.880005  758.880005  769.500000  758.340027  769.500000
           MSFT    52.818901   55.480000   56.189999   55.419998   56.040001
2015-12-30 AAPL   103.322678  107.320000  108.699997  107.180000  108.580002
           AMZN   689.070007  689.070007  695.489990  686.380005  691.890015
           GOOG   771.000000  771.000000  777.599976  766.900024  776.599976
           MSFT    53.609093   56.310001   56.779999   56.290001   56.470001
2015-12-29 AAPL   104.689766  108.739998  109.430000  106.860001  106.959999
           AMZN   693.969971  693.969971  696.440002  677.890015  677.979980
           GOOG   776.599976  776.599976  779.979980  766.429993  766.690002
           MSFT    53.837578   56.549999   56.849998   56.060001   56.290001
2015-12-28 AAPL   102.841293  106.820000  107.690002  106.180000  107.589996
           AMZN   675.200012  675.200012  675.500000  665.500000  665.559998
           GOOG   762.510010  762.510010  762.989990  749.520020  752.919983
           MSFT    53.266361   55.950001   55.950001   54.980000   55.349998
2015-12-24 AAPL   104.006226  108.029999  109.000000  107.949997  109.000000
           AMZN   662.789978  662.789978  664.679993  660.599976  663.349976
           GOOG   748.400024  748.400024  751.349976  746.619995  749.549988
           MSFT    52.999783   55.669998   55.959999   55.430000   55.860001
2015-12-23 AAPL   104.564606  108.610001  108.849998  107.199997  107.269997
           AMZN   663.700012  663.700012  666.599976  656.630005  666.500000
           GOOG   750.309998  750.309998  754.210022  744.000000  753.469971
           MSFT    53.142597   55.820000   55.880001   55.439999   55.700001
2015-12-22 AAPL   103.236031  107.230003  107.720001  106.449997  107.400002
           AMZN   663.150024  663.150024  668.489990  659.260010  666.830017
           GOOG   750.000000  750.000000  754.849976  745.530029  751.650024
           MSFT    52.695137   55.349998   55.480000   54.500000   54.990002
2015-12-21 AAPL   103.332298  107.330002  107.370003  105.570000  107.279999
           AMZN   664.510010  664.510010  669.900024  658.929993  668.500000
...                      ...         ...         ...         ...         ...
2010-01-12 GOOG   293.332153  293.332153  297.147339  292.100159  296.893982
           MSFT    24.433821   30.070000   30.400000   29.910000   30.150000
2010-01-11 AAPL    26.907093   30.015715   30.428572   29.778572   30.400000
           AMZN   130.309998  130.309998  132.800003  129.210007  132.619995
           GOOG   298.612823  298.612823  300.276978  295.100647  300.276978
           MSFT    24.596333   30.270000   30.760000   30.120001   30.709999
2010-01-08 AAPL    27.146566   30.282858   30.285715   29.865715   30.042856
           AMZN   133.520004  133.520004  133.679993  129.029999  130.559998
           GOOG   299.064880  299.064880  299.675903  292.651581  294.087250
           MSFT    24.913233   30.660000   30.879999   30.240000   30.280001
2010-01-07 AAPL    26.967278   30.082857   30.285715   29.864286   30.250000
           AMZN   130.000000  130.000000  132.320007  128.800003  132.009995
           GOOG   295.130463  295.130463  303.029083  294.410156  302.731018
           MSFT    24.742592   30.450001   30.700001   30.190001   30.629999
2010-01-06 AAPL    27.017223   30.138571   30.747143   30.107143   30.625713
           AMZN   132.250000  132.250000  134.729996  131.649994  134.600006
           GOOG   302.164703  302.164703  310.907837  301.220856  310.907837
           MSFT    25.002611   30.770000   31.080000   30.520000   30.879999
2010-01-05 AAPL    27.453915   30.625713   30.798571   30.464285   30.657143
           AMZN   134.690002  134.690002  135.479996  131.809998  133.429993
           GOOG   309.978882  309.978882  311.891449  308.761810  311.563568
           MSFT    25.157001   30.959999   31.100000   30.639999   30.850000
2010-01-04 AAPL    27.406532   30.572857   30.642857   30.340000   30.490000
           AMZN   133.899994  133.899994  136.610001  133.139999  136.250000
           GOOG   311.349976  311.349976  312.721039  310.103088  311.449310
           MSFT    25.148876   30.950001   31.100000   30.590000   30.620001
2009-12-31 AAPL    26.986492   30.104286   30.478571   30.080000   30.447144
           AMZN   134.520004  134.520004  137.279999  134.520004  137.089996
           GOOG   307.986847  307.986847  310.679321  307.986847  310.356445
           MSFT    24.766968   30.480000   30.990000   30.480000   30.980000

                       Volume
Date       minor
2015-12-31 AAPL    40635300.0
           AMZN     3749600.0
           GOOG     1500900.0
           MSFT    27334100.0
2015-12-30 AAPL    25213800.0
           AMZN     3519000.0
           GOOG     1293300.0
           MSFT    21704500.0
2015-12-29 AAPL    30931200.0
           AMZN     5735000.0
           GOOG     1765000.0
           MSFT    27731400.0
2015-12-28 AAPL    26704200.0
           AMZN     3775800.0
           GOOG     1515300.0
           MSFT    21698000.0
2015-12-24 AAPL    13570400.0
           AMZN     1093000.0
           GOOG      527200.0
           MSFT     9570000.0
2015-12-23 AAPL    32657400.0
           AMZN     2722900.0
           GOOG     1565900.0
           MSFT    27279800.0
2015-12-22 AAPL    32789400.0
           AMZN     2664000.0
           GOOG     1365400.0
           MSFT    28300300.0
2015-12-21 AAPL    47590600.0
           AMZN     3250900.0
...                       ...
2010-01-12 GOOG     9769600.0
           MSFT    65912100.0
2010-01-11 AAPL   115557400.0
           AMZN     8779400.0
           GOOG    14519600.0
           MSFT    68754700.0
2010-01-08 AAPL   111902700.0
           AMZN     9830500.0
           GOOG     9509900.0
           MSFT    51197400.0
2010-01-07 AAPL   119282800.0
           AMZN    11030200.0
           GOOG    12912000.0
           MSFT    50559700.0
2010-01-06 AAPL   138040000.0
           AMZN     7178800.0
           GOOG     8009000.0
           MSFT    58182400.0
2010-01-05 AAPL   150476200.0
           AMZN     8851900.0
           GOOG     6048500.0
           MSFT    49749600.0
2010-01-04 AAPL   123432400.0
           AMZN     7599900.0
           GOOG     3937800.0
           MSFT    38409100.0
2009-12-31 AAPL    88102700.0
           AMZN     4523000.0
           GOOG     2455400.0
           MSFT    31929700.0

[6044 rows x 6 columns]

In [56]:
p.items

Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object')

In [55]:
p.major_axis

DatetimeIndex(['2015-12-31', '2015-12-30', '2015-12-29', '2015-12-28',
               '2015-12-24', '2015-12-23', '2015-12-22', '2015-12-21',
               '2015-12-18', '2015-12-17',
               ...
               '2010-01-14', '2010-01-13', '2010-01-12', '2010-01-11',
               '2010-01-08', '2010-01-07', '2010-01-06', '2010-01-05',
               '2010-01-04', '2009-12-31'],
              dtype='datetime64[ns]', name='Date', length=1511, freq=None)

In [58]:
p.major_xs("2015-12-31")

<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 1 (major_axis) x 4 (minor_axis)
Items axis: Adj Close to Volume
Major_axis axis: 2015-12-31 00:00:00 to 2015-12-31 00:00:00
Minor_axis axis: AAPL to MSFT

In [57]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 6 (items) x 1511 (major_axis) x 4 (minor_axis)
Items axis: Adj Close to Volume
Major_axis axis: 2015-12-31 00:00:00 to 2009-12-31 00:00:00
Minor_axis axis: AAPL to MSFT

In [61]:
p.minor_axis

Index(['AAPL', 'AMZN', 'GOOG', 'MSFT'], dtype='object')

In [62]:
p.minor_xs('AAPL')

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2015-12-31,101.339394,105.260002,107.029999,104.820000,107.010002,40635300.0
2015-12-30,103.322678,107.320000,108.699997,107.180000,108.580002,25213800.0
2015-12-29,104.689766,108.739998,109.430000,106.860001,106.959999,30931200.0
2015-12-28,102.841293,106.820000,107.690002,106.180000,107.589996,26704200.0
2015-12-24,104.006226,108.029999,109.000000,107.949997,109.000000,13570400.0
2015-12-23,104.564606,108.610001,108.849998,107.199997,107.269997,32657400.0
2015-12-22,103.236031,107.230003,107.720001,106.449997,107.400002,32789400.0
2015-12-21,103.332298,107.330002,107.370003,105.570000,107.279999,47590600.0
2015-12-18,102.080704,106.029999,109.519997,105.809998,108.910004,96453300.0
2015-12-17,104.920845,108.980003,112.250000,108.980003,112.019997,44772800.0
2015-12-16,107.192924,111.339996,111.989998,108.800003,111.070000,56238500.0
2015-12-15,106.374588,110.489998,112.800003,110.349998,111.940002,53323100.0
2015-12-14,108.290482,112.480003,112.680000,109.790001,112.180000,64318700.0
2015-12-11,108.964409,113.180000,115.389999,112.849998,115.190002,46886200.0
2015-12-10,111.843025,116.169998,116.940002,115.510002,116.040001,29104200.0
2015-12-09,111.313515,115.620003,117.690002,115.080002,117.639999,46361400.0
2015-12-08,113.826294,118.230003,118.599998,116.860001,117.519997,34309500.0
2015-12-07,113.874435,118.279999,119.860001,117.809998,118.980003,32084200.0
2015-12-04,114.596504,119.029999,119.250000,115.110001,115.290001,57777000.0
2015-12-03,110.909157,115.199997,116.790001,114.220001,116.550003,41569500.0
2015-12-02,111.948929,116.279999,118.110001,116.080002,117.339996,33386600.0
2015-12-01,112.969444,117.339996,118.809998,116.860001,118.750000,34852400.0
2015-11-30,113.893692,118.300003,119.410004,117.750000,117.989998,39180300.0
2015-11-27,113.421944,117.809998,118.410004,117.599998,118.290001,13046400.0
2015-11-25,113.633751,118.029999,119.230003,117.919998,119.209999,21388300.0
2015-11-24,114.452087,118.879997,119.349998,117.120003,117.330002,42803200.0
2015-11-23,113.364174,117.750000,119.730003,117.339996,119.269997,32482500.0
2015-11-20,114.856453,119.300003,119.919998,118.849998,119.199997,34287100.0
2015-11-19,114.355820,118.779999,119.750000,116.760002,117.639999,43295800.0
2015-11-18,112.921310,117.290001,117.489998,115.500000,115.760002,46674700.0
...,...,...,...,...,...,...
2010-02-12,25.661045,28.625713,28.805714,27.928572,28.301428,163867200.0
2010-02-11,25.442059,28.381428,28.535715,27.722857,27.840000,137586400.0
2010-02-10,24.987444,27.874287,28.085714,27.751429,27.984285,92590400.0
2010-02-09,25.124472,28.027143,28.214285,27.821428,28.059999,158221700.0
2010-02-08,24.859381,27.731428,28.268572,27.714285,27.955715,119567700.0
2010-02-05,25.030981,27.922857,28.000000,27.264286,27.518572,212576700.0
2010-02-04,24.594294,27.435715,28.338572,27.367144,28.104286,189413000.0
2010-02-03,25.513775,28.461428,28.600000,27.774286,27.881428,153832000.0
2010-02-02,25.082211,27.980000,28.045713,27.625713,27.987143,174585600.0
2010-02-01,24.937496,27.818571,28.000000,27.328571,27.481428,187469100.0
2010-01-29,24.595573,27.437143,28.885714,27.178572,28.725714,311488100.0
2010-01-28,25.521461,28.469999,29.357143,28.385714,29.275715,293375600.0
2010-01-27,26.621517,29.697144,30.082857,28.504286,29.549999,430642100.0
2010-01-26,26.373072,29.420000,30.530001,28.940001,29.421429,466777500.0
2010-01-25,26.005541,29.010000,29.242857,28.598572,28.930000,266424900.0
2010-01-22,25.324244,28.250000,29.642857,28.165714,29.540001,220441900.0
2010-01-21,26.645842,29.724285,30.472857,29.601429,30.297142,152038600.0
2010-01-20,27.114555,30.247143,30.792856,29.928572,30.701429,153038200.0
2010-01-19,27.538433,30.719999,30.741428,29.605715,29.761429,182501900.0
2010-01-15,26.371792,29.418571,30.228571,29.410000,30.132856,148516900.0
2010-01-14,26.820007,29.918571,30.065714,29.860001,30.015715,108223500.0
2010-01-13,26.976244,30.092857,30.132856,29.157143,29.695715,151473000.0
2010-01-12,26.601023,29.674286,29.967142,29.488571,29.884285,148614900.0
2010-01-11,26.907093,30.015715,30.428572,29.778572,30.400000,115557400.0
2010-01-08,27.146566,30.282858,30.285715,29.865715,30.042856,111902700.0
2010-01-07,26.967278,30.082857,30.285715,29.864286,30.250000,119282800.0
2010-01-06,27.017223,30.138571,30.747143,30.107143,30.625713,138040000.0
2010-01-05,27.453915,30.625713,30.798571,30.464285,30.657143,150476200.0
2010-01-04,27.406532,30.572857,30.642857,30.340000,30.490000,123432400.0
2009-12-31,26.986492,30.104286,30.478571,30.080000,30.447144,88102700.0

In [63]:
p.axes

[Index(['Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='object'),
 DatetimeIndex(['2015-12-31', '2015-12-30', '2015-12-29', '2015-12-28',
                '2015-12-24', '2015-12-23', '2015-12-22', '2015-12-21',
                '2015-12-18', '2015-12-17',
                ...
                '2010-01-14', '2010-01-13', '2010-01-12', '2010-01-11',
                '2010-01-08', '2010-01-07', '2010-01-06', '2010-01-05',
                '2010-01-04', '2009-12-31'],
               dtype='datetime64[ns]', name='Date', length=1511, freq=None),
 Index(['AAPL', 'AMZN', 'GOOG', 'MSFT'], dtype='object')]

In [65]:
p2 = p.transpose(2,1,0)

In [66]:
p2

<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 1511 (major_axis) x 6 (minor_axis)
Items axis: AAPL to MSFT
Major_axis axis: 2015-12-31 00:00:00 to 2009-12-31 00:00:00
Minor_axis axis: Adj Close to Volume

In [69]:
p2.major_axis

p.major_axis

DatetimeIndex(['2015-12-31', '2015-12-30', '2015-12-29', '2015-12-28',
               '2015-12-24', '2015-12-23', '2015-12-22', '2015-12-21',
               '2015-12-18', '2015-12-17',
               ...
               '2010-01-14', '2010-01-13', '2010-01-12', '2010-01-11',
               '2010-01-08', '2010-01-07', '2010-01-06', '2010-01-05',
               '2010-01-04', '2009-12-31'],
              dtype='datetime64[ns]', name='Date', length=1511, freq=None)

In [71]:
p2.minor_axis

p.minor_axis

Index(['AAPL', 'AMZN', 'GOOG', 'MSFT'], dtype='object')

In [74]:
p2['GOOG']

,Adj Close,Close,High,Low,Open,Volume
Date,,,,,,
2015-12-31,758.880005,758.880005,769.500000,758.340027,769.500000,1500900.0
2015-12-30,771.000000,771.000000,777.599976,766.900024,776.599976,1293300.0
2015-12-29,776.599976,776.599976,779.979980,766.429993,766.690002,1765000.0
2015-12-28,762.510010,762.510010,762.989990,749.520020,752.919983,1515300.0
2015-12-24,748.400024,748.400024,751.349976,746.619995,749.549988,527200.0
2015-12-23,750.309998,750.309998,754.210022,744.000000,753.469971,1565900.0
2015-12-22,750.000000,750.000000,754.849976,745.530029,751.650024,1365400.0
2015-12-21,747.770020,747.770020,750.000000,740.000000,746.130005,1525700.0
2015-12-18,739.309998,739.309998,754.130005,738.150024,746.510010,3148700.0
2015-12-17,749.429993,749.429993,762.679993,749.000000,762.419983,1553400.0
2015-12-16,758.090027,758.090027,760.590027,739.434998,750.000000,1993300.0
2015-12-15,743.400024,743.400024,758.080017,743.010010,753.000000,2666200.0
2015-12-14,747.770020,747.770020,748.729980,724.169983,741.789978,2412500.0
2015-12-11,738.869995,738.869995,745.710022,736.750000,741.159973,2224400.0
2015-12-10,749.460022,749.460022,755.849976,743.830017,752.849976,1984900.0
2015-12-09,751.609985,751.609985,764.229980,737.000977,759.169983,2700000.0
2015-12-08,762.369995,762.369995,764.799988,754.200012,757.890015,1829500.0
2015-12-07,763.250000,763.250000,768.729980,755.090027,767.770020,1812300.0
2015-12-04,766.809998,766.809998,768.489990,750.000000,753.099976,2757300.0
2015-12-03,752.539978,752.539978,768.994995,745.630005,766.010010,2590600.0
2015-12-02,762.380005,762.380005,775.955017,758.960022,768.900024,2230400.0
2015-12-01,767.039978,767.039978,768.950012,746.700012,747.109985,2134600.0
2015-11-30,742.599976,742.599976,754.929993,741.270020,748.809998,2097600.0
2015-11-27,750.260010,750.260010,753.409973,747.489990,748.460022,838500.0
2015-11-25,748.150024,748.150024,752.000000,746.059998,748.140015,1122100.0
2015-11-24,748.280029,748.280029,755.278992,737.630005,752.000000,2333100.0
2015-11-23,755.979980,755.979980,762.708008,751.820007,757.450012,1414500.0
2015-11-20,756.599976,756.599976,757.919983,743.000000,746.530029,2212300.0
2015-11-19,738.409973,738.409973,742.000000,737.429993,738.739990,1327100.0
2015-11-18,740.000000,740.000000,741.409973,727.000000,727.580017,1684300.0
...,...,...,...,...,...,...
2010-02-12,264.837494,264.837494,266.839478,263.535950,264.762970,4589000.0
2010-02-11,266.466888,266.466888,268.498688,263.039185,264.936829,4851300.0
2010-02-10,265.498199,265.498199,267.157410,262.140045,265.309418,5383700.0
2010-02-09,266.486755,266.486755,269.015320,265.806183,268.026733,5675700.0
2010-02-08,265.011353,265.011353,269.248810,264.047638,264.529480,5423500.0
2010-02-05,263.928406,263.928406,265.026245,259.541931,262.492737,6353000.0
2010-02-04,261.687958,261.687958,267.261719,261.081909,266.764954,6799200.0
2010-02-03,268.662598,268.662598,269.298462,262.408295,262.626862,6037000.0
2010-02-02,263.843964,263.843964,265.751556,262.100281,265.751556,8245600.0
2010-02-01,264.787811,264.787811,266.173798,263.436584,265.572693,4530800.0
2010-01-29,263.257751,263.257751,268.747070,261.106750,267.505127,8334700.0
2010-01-28,265.418701,265.418701,271.732635,263.585632,270.485748,6500100.0
2010-01-27,269.298462,269.298462,272.055542,265.925415,268.886169,7980200.0
2010-01-26,269.457428,269.457428,273.024231,266.412231,267.246826,8767600.0
2010-01-25,268.255249,268.255249,273.163330,266.024780,271.528961,8897200.0
2010-01-22,273.227905,273.227905,283.456390,265.701874,280.426086,13689200.0
2010-01-21,289.606384,289.606384,291.513977,284.276062,289.834900,12697400.0
2010-01-20,288.329681,288.329681,291.096710,285.786224,291.096710,6543600.0
2010-01-19,291.911407,291.911407,293.302338,286.283020,288.722137,8689500.0
2010-01-15,288.126007,288.126007,294.862213,287.152344,294.752930,10939600.0
2010-01-14,293.019196,293.019196,295.180145,289.521942,290.063416,8535300.0
2010-01-13,291.648102,291.648102,292.288940,285.095734,286.382355,13077600.0
2010-01-12,293.332153,293.332153,297.147339,292.100159,296.893982,9769600.0
2010-01-11,298.612823,298.612823,300.276978,295.100647,300.276978,14519600.0
2010-01-08,299.064880,299.064880,299.675903,292.651581,294.087250,9509900.0
2010-01-07,295.130463,295.130463,303.029083,294.410156,302.731018,12912000.0
2010-01-06,302.164703,302.164703,310.907837,301.220856,310.907837,8009000.0
2010-01-05,309.978882,309.978882,311.891449,308.761810,311.563568,6048500.0
2010-01-04,311.349976,311.349976,312.721039,310.103088,311.449310,3937800.0
2009-12-31,307.986847,307.986847,310.679321,307.986847,310.356445,2455400.0

In [75]:
p2 = p.swapaxes("items","minor")

/Users/siva/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning:
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  """Entry point for launching an IPython kernel.

In [76]:
p2

<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 1511 (major_axis) x 6 (minor_axis)
Items axis: AAPL to MSFT
Major_axis axis: 2015-12-31 00:00:00 to 2009-12-31 00:00:00
Minor_axis axis: Adj Close to Volume

In [78]:
p2['MSFT']

            Adj Close      Close       High        Low       Open       Volume
Date
2015-12-31  52.818901  55.480000  56.189999  55.419998  56.040001   27334100.0
2015-12-30  53.609093  56.310001  56.779999  56.290001  56.470001   21704500.0
2015-12-29  53.837578  56.549999  56.849998  56.060001  56.290001   27731400.0
2015-12-28  53.266361  55.950001  55.950001  54.980000  55.349998   21698000.0
2015-12-24  52.999783  55.669998  55.959999  55.430000  55.860001    9570000.0
2015-12-23  53.142597  55.820000  55.880001  55.439999  55.700001   27279800.0
2015-12-22  52.695137  55.349998  55.480000  54.500000  54.990002   28300300.0
2015-12-21  52.200081  54.830002  55.349998  54.230000  54.880001   37246300.0
2015-12-18  51.533657  54.130001  56.000000  54.029999  55.770000   84684200.0
2015-12-17  53.028351  55.700001  56.790001  55.529999  56.360001   41280900.0
2015-12-16  53.437721  56.130001  56.250000  54.759998  55.540001   37503300.0
2015-12-15  52.552334  55.200001  55.900002  55.090000  55.660000   39843000.0
2015-12-14  52.495205  55.139999  55.209999  53.680000  54.330002   46768900.0
2015-12-11  51.467010  54.060001  55.099998  54.009998  54.709999   39549500.0
2015-12-10  52.618977  55.270000  55.660000  55.009998  55.389999   31620700.0
2015-12-09  52.342884  54.980000  55.869999  54.509998  55.369999   36373200.0
2015-12-08  53.114033  55.790001  56.099998  54.990002  55.470001   32878000.0
2015-12-07  53.133072  55.810001  55.970001  55.290001  55.790001   30709800.0
2015-12-04  53.228275  55.910000  56.230000  54.099998  54.119999   43963700.0
2015-12-03  51.600296  54.200001  55.770000  53.930000  55.490002   38627800.0
2015-12-02  52.561848  55.209999  55.959999  55.060001  55.320000   47274900.0
2015-12-01  52.571377  55.220001  55.230000  54.299999  54.410000   39952800.0
2015-11-30  51.743099  54.349998  54.959999  54.000000  54.540001   56241400.0
2015-11-27  51.343243  53.930000  54.080002  53.790001  53.799999    9009100.0
2015-11-25  51.114758  53.689999  54.230000  53.689999  54.090000   21005100.0
2015-11-24  51.647903  54.250000  54.439999  53.580002  53.919998   24600000.0
2015-11-23  51.590775  54.189999  54.459999  53.750000  54.250000   28235900.0
2015-11-20  51.590775  54.189999  54.299999  53.270000  54.250000   37147600.0
2015-11-19  51.352764  53.939999  54.660000  53.779999  53.990002   28149200.0
2015-11-18  51.267082  53.849998  53.980000  52.980000  53.000000   29710000.0
...               ...        ...        ...        ...        ...          ...
2010-02-12  22.694933  27.930000  28.059999  27.580000  27.809999   81117200.0
2010-02-11  22.849319  28.120001  28.400000  27.700001  27.930000   65993700.0
2010-02-10  22.743685  27.990000  28.240000  27.840000  28.030001   48591300.0
2010-02-09  22.759937  28.010000  28.340000  27.750000  27.969999   59195800.0
2010-02-08  22.524290  27.719999  28.080000  27.570000  28.010000   52820600.0
2010-02-05  22.768064  28.020000  28.280001  27.570000  28.000000   80960100.0
2010-02-04  22.621799  27.840000  28.500000  27.809999  28.379999   77850000.0
2010-02-03  23.263727  28.629999  28.790001  28.120001  28.260000   61397900.0
2010-02-02  23.125591  28.459999  28.500000  28.139999  28.370001   54413700.0
2010-02-01  23.084957  28.410000  28.480000  27.920000  28.389999   85931100.0
2010-01-29  22.898075  28.180000  29.920000  27.660000  29.900000  193888500.0
2010-01-28  23.694384  29.160000  29.870001  28.889999  29.840000  117513700.0
2010-01-27  24.108797  29.670000  29.820000  29.020000  29.350000   63949500.0
2010-01-26  23.970657  29.500000  29.850000  29.090000  29.200001   66639900.0
2010-01-25  23.824394  29.320000  29.660000  29.100000  29.240000   63373000.0
2010-01-22  23.531868  28.959999  30.200001  28.840000  30.000000  102004600.0
2010-01-21  24.385063  30.010000  30.719999  30.000000  30.610001   73086700.0
2010-01-20  24.856350  30.590000  30.940001  30.309999  30.809999   54849500.0
2010-01-19  25.270758  31.100000  31.240000  30.680000  30.750000   46575700.0
2010-01-15  25.075747  30.860001  31.240000  30.709999  31.080000   79913200.0
2010-01-14  25.157001  30.959999  31.100000  30.260000  30.309999   63228100.0
2010-01-13  24.661339  30.350000  30.520000  30.010000  30.260000   51863500.0
2010-01-12  24.433821  30.070000  30.400000  29.910000  30.150000   65912100.0
2010-01-11  24.596333  30.270000  30.760000  30.120001  30.709999   68754700.0
2010-01-08  24.913233  30.660000  30.879999  30.240000  30.280001   51197400.0
2010-01-07  24.742592  30.450001  30.700001  30.190001  30.629999   50559700.0
2010-01-06  25.002611  30.770000  31.080000  30.520000  30.879999   58182400.0
2010-01-05  25.157001  30.959999  31.100000  30.639999  30.850000   49749600.0
2010-01-04  25.148876  30.950001  31.100000  30.590000  30.620001   38409100.0
2009-12-31  24.766968  30.480000  30.990000  30.480000  30.980000   31929700.0

[1511 rows x 6 columns]